/*! PhotoSwipe - v4.1.0 - 2015-07-23
* http://photoswipe.com
* Copyright (c) 2015 Dmitry Semenov; */

/*! PhotoSwipe Default UI - 4.1.0 - 2015-07-11
* http://photoswipe.com
* Copyright (c) 2015 Dmitry Semenov; */
/**
*
* UI on top of main sliding area (caption, arrows, close button, etc.).
* Built just using public methods/properties of PhotoSwipe.
* 
*/

/* 	JIGphotoSwipe(); jQuery wrapper made exclusively for JIG v2.9 by Firsh
 		Additional changes to original PhotoSwipe:
			photoswipe-ui-default.js
				_updateShareURLs
			photoswipe.js - affected functions:
				History
					_parseItemIndexFromURL
					_updateHash
					publicMethods:
						initHistory
						onHashChange
*/

(function(d,h){"function"===typeof define&&define.amd?define(h):"object"===typeof exports?module.exports=h():d.PhotoSwipe=h()})(this,function(){return function(d,h,p,ra){var f={features:null,bind:function(a,b,c,k){k=(k?"remove":"add")+"EventListener";b=b.split(" ");for(var e=0;e<b.length;e++)if(b[e])a[k](b[e],c,!1)},isArray:function(a){return a instanceof Array},createEl:function(a,b){var c=document.createElement(b||"div");a&&(c.className=a);return c},getScrollY:function(){var a=window.pageYOffset;
return void 0!==a?a:document.documentElement.scrollTop},unbind:function(a,b,c){f.bind(a,b,c,!0)},removeClass:function(a,b){a.className=a.className.replace(new RegExp("(\\s|^)"+b+"(\\s|$)")," ").replace(/^\s\s*/,"").replace(/\s\s*$/,"")},addClass:function(a,b){f.hasClass(a,b)||(a.className+=(a.className?" ":"")+b)},hasClass:function(a,b){return a.className&&(new RegExp("(^|\\s)"+b+"(\\s|$)")).test(a.className)},getChildByClass:function(a,b){for(var c=a.firstChild;c;){if(f.hasClass(c,b))return c;c=
c.nextSibling}},arraySearch:function(a,b,c){for(var k=a.length;k--;)if(a[k][c]===b)return k;return-1},extend:function(a,b,c){for(var k in b)!b.hasOwnProperty(k)||c&&a.hasOwnProperty(k)||(a[k]=b[k])},easing:{sine:{out:function(a){return Math.sin(Math.PI/2*a)},inOut:function(a){return-(Math.cos(Math.PI*a)-1)/2}},cubic:{out:function(a){return--a*a*a+1}}},detectFeatures:function(){if(f.features)return f.features;var a=f.createEl().style,b="",c={};c.oldIE=document.all&&!document.addEventListener;c.touch=
"ontouchstart"in window;window.requestAnimationFrame&&(c.raf=window.requestAnimationFrame,c.caf=window.cancelAnimationFrame);c.pointerEvent=navigator.pointerEnabled||navigator.msPointerEnabled;if(!c.pointerEvent){b=navigator.userAgent;if(/iP(hone|od)/.test(navigator.platform)){var k=navigator.appVersion.match(/OS (\d+)_(\d+)_?(\d+)?/);k&&0<k.length&&(k=parseInt(k[1],10),1<=k&&8>k&&(c.isOldIOSPhone=!0))}k=(k=b.match(/Android\s([0-9\.]*)/))?k[1]:0;k=parseFloat(k);1<=k&&(4.4>k&&(c.isOldAndroid=!0),c.androidVersion=
k);c.isMobileOpera=/opera mini|opera mobi/i.test(b)}for(var k=["transform","perspective","animationName"],e=["","webkit","Moz","ms","O"],d,n,g=0;4>g;g++){for(var b=e[g],h=0;3>h;h++)d=k[h],n=b+(b?d.charAt(0).toUpperCase()+d.slice(1):d),!c[d]&&n in a&&(c[d]=n);b&&!c.raf&&(b=b.toLowerCase(),c.raf=window[b+"RequestAnimationFrame"],c.raf&&(c.caf=window[b+"CancelAnimationFrame"]||window[b+"CancelRequestAnimationFrame"]))}if(!c.raf){var m=0;c.raf=function(a){var b=(new Date).getTime(),c=Math.max(0,16-(b-
m)),k=window.setTimeout(function(){a(b+c)},c);m=b+c;return k};c.caf=function(a){clearTimeout(a)}}c.svg=!!document.createElementNS&&!!document.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect;return f.features=c}};f.detectFeatures();f.features.oldIE&&(f.bind=function(a,b,c,k){b=b.split(" ");for(var e=(k?"detach":"attach")+"Event",d,n=function(){c.handleEvent.call(c)},f=0;f<b.length;f++)if(d=b[f])if("object"===typeof c&&c.handleEvent){if(!k)c["oldIE"+d]=n;else if(!c["oldIE"+d])return!1;
a[e]("on"+d,c["oldIE"+d])}else a[e]("on"+d,c)});var e=this,g={allowPanToNext:!0,spacing:.12,bgOpacity:1,mouseUsed:!1,loop:!0,pinchToClose:!0,closeOnScroll:!0,closeOnVerticalDrag:!0,verticalDragRange:.75,hideAnimationDuration:333,showAnimationDuration:333,showHideOpacity:!1,focus:!0,escKey:!0,arrowKeys:!0,mainScrollEndFriction:.35,panEndFriction:.35,isClickableElement:function(a){return"A"===a.tagName},getDoubleTapZoom:function(a,b){return a?1:.7>b.initialZoomLevel?1:1.33},maxSpreadZoom:1.33,modal:!0,
scaleMode:"fit"};f.extend(g,ra);var A=function(){return{x:0,y:0}},z,Ua,Ea,l,D,E,K=A(),v=A(),m=A(),ba,ha,B,q={},t,R,Fa,W,Ga,sa,F=0,ia={},L=A(),x,Ha,G=0,ja,ka,la,Ia,U,ca,Ja=!0,V,ma=[],Ka,n,C,Rb,vb,ta,w,Va={},La=!1,Wa=function(a,b){f.extend(e,b.publicMethods);ma.push(a)},jb=function(a){var b=P();return a>b-1?a-b:0>a?b+a:a},Xa={},y=function(a,b){Xa[a]||(Xa[a]=[]);return Xa[a].push(b)},u=function(a){var b=Xa[a];if(b){var c=Array.prototype.slice.call(arguments);c.shift();for(var k=0;k<b.length;k++)b[k].apply(e,
c)}},X=function(){return(new Date).getTime()},da=function(a){kb=a;e.bg.style.opacity=a*g.bgOpacity},Sb=function(a,b,c,k,d){if(!La||d&&d!==e.currItem)k/=d?d.fitRatio:e.currItem.fitRatio;a[U]=Fa+b+"px, "+c+"px"+W+" scale("+k+")"},H=function(a){ea&&(a&&(t>e.currItem.fitRatio?La||(ua(e.currItem,!1,!0),La=!0):La&&(ua(e.currItem),La=!1)),Sb(ea,m.x,m.y,t))},Ya=function(a){a.container&&Sb(a.container.style,a.initialPosition.x,a.initialPosition.y,a.initialZoomLevel,a)},Ma=function(a,b){b[U]=Fa+a+"px, 0px"+
W},lb=function(a,b){if(!g.loop&&b){var c=l+(L.x*F-a)/L.x,k=Math.round(a-fa.x);if(0>c&&0<k||c>=P()-1&&0>k)a=fa.x+k*g.mainScrollEndFriction}fa.x=a;Ma(a,D)},wb=function(a,b){var c=Za[a]-ia[a];return v[a]+K[a]+c-b/R*c},M=function(a,b){a.x=b.x;a.y=b.y;b.id&&(a.id=b.id)},Tb=function(a){a.x=Math.round(a.x);a.y=Math.round(a.y)},xb=null,yb=function(){xb&&(f.unbind(document,"mousemove",yb),f.addClass(d,"pswp--has_mouse"),g.mouseUsed=!0,u("mouseUsed"));xb=setTimeout(function(){xb=null},100)},zb=function(a,b){var c=
$a(e.currItem,q,a);b&&(r=c);return c},Ub=function(a){a||(a=e.currItem);return a.initialZoomLevel},Vb=function(a){a||(a=e.currItem);return 0<a.w?g.maxSpreadZoom:1},Wb=function(a,b,c,k){if(k===e.currItem.initialZoomLevel)return c[a]=e.currItem.initialPosition[a],!0;c[a]=wb(a,k);return c[a]>b.min[a]?(c[a]=b.min[a],!0):c[a]<b.max[a]?(c[a]=b.max[a],!0):!1},oc=function(){U?(Fa="translate"+(w.perspective&&!V?"3d(":"("),W=w.perspective?", 0px)":")"):(U="left",f.addClass(d,"pswp--ie"),Ma=function(a,b){b.left=
a+"px"},Ya=function(a){var b=1<a.fitRatio?1:a.fitRatio,c=a.container.style,k=b*a.h;c.width=b*a.w+"px";c.height=k+"px";c.left=a.initialPosition.x+"px";c.top=a.initialPosition.y+"px"},H=function(){if(ea){var a=ea,b=e.currItem,c=1<b.fitRatio?1:b.fitRatio,k=c*b.h;a.width=c*b.w+"px";a.height=k+"px";a.left=m.x+"px";a.top=m.y+"px"}})},pc=function(a){var b="";g.escKey&&27===a.keyCode?b="close":g.arrowKeys&&(37===a.keyCode?b="prev":39===a.keyCode&&(b="next"));!b||a.ctrlKey||a.altKey||a.shiftKey||a.metaKey||
(a.preventDefault?a.preventDefault():a.returnValue=!1,e[b]())},qc=function(a){a&&(Na||va||N||ab)&&(a.preventDefault(),a.stopPropagation())},Xb=function(){e.setScrollOffset(0,f.getScrollY())},Q={},Oa=0,bb=function(a){Q[a]&&(Q[a].raf&&n(Q[a].raf),Oa--,delete Q[a])},Ab=function(a){Q[a]&&bb(a);Q[a]||(Oa++,Q[a]={})},cb=function(){for(var a in Q)Q.hasOwnProperty(a)&&bb(a)},db=function(a,b,c,k,e,d,n){var f=X(),g;Ab(a);var h=function(){Q[a]&&(g=X()-f,g>=k?(bb(a),d(c),n&&n()):(d((c-b)*e(g/k)+b),Q[a].raf=Ka(h)))};
h()},rc={shout:u,listen:y,viewportSize:q,options:g,isMainScrollAnimating:function(){return N},getZoomLevel:function(){return t},getCurrentIndex:function(){return l},isDragging:function(){return Y},isZooming:function(){return ga},setScrollOffset:function(a,b){ia.x=a;ta=ia.y=b;u("updateScrollOffset",ia)},applyZoomPan:function(a,b,c,k){m.x=b;m.y=c;t=a;H(k)},init:function(){if(!z&&!Ua){var a;e.framework=f;e.template=d;e.bg=f.getChildByClass(d,"pswp__bg");C=d.className;z=!0;w=f.detectFeatures();Ka=w.raf;
n=w.caf;U=w.transform;vb=w.oldIE;e.scrollWrap=f.getChildByClass(d,"pswp__scroll-wrap");e.container=f.getChildByClass(e.scrollWrap,"pswp__container");D=e.container.style;e.itemHolders=x=[{el:e.container.children[0],wrap:0,index:-1},{el:e.container.children[1],wrap:0,index:-1},{el:e.container.children[2],wrap:0,index:-1}];x[0].el.style.display=x[2].el.style.display="none";oc();B={resize:e.updateSize,scroll:Xb,keydown:pc,click:qc};a=w.isOldIOSPhone||w.isOldAndroid||w.isMobileOpera;w.animationName&&w.transform&&
!a||(g.showAnimationDuration=g.hideAnimationDuration=0);for(a=0;a<ma.length;a++)e["init"+ma[a]]();h&&(e.ui=new h(e,f)).init();u("firstUpdate");l=l||g.index||0;if(isNaN(l)||0>l||l>=P())l=0;e.currItem=wa(l);if(w.isOldIOSPhone||w.isOldAndroid)Ja=!1;d.setAttribute("aria-hidden","false");g.modal&&(Ja?d.style.position="fixed":(d.style.position="absolute",d.style.top=f.getScrollY()+"px"));void 0===ta&&(u("initialLayout"),ta=Rb=f.getScrollY());a="pswp--open ";g.mainClass&&(a+=g.mainClass+" ");g.showHideOpacity&&
(a+="pswp--animate_opacity ");a+=V?"pswp--touch":"pswp--notouch";a+=w.animationName?" pswp--css_animation":"";a+=w.svg?" pswp--svg":"";f.addClass(d,a);e.updateSize();E=-1;G=null;for(a=0;3>a;a++)Ma((a+E)*L.x,x[a].el.style);vb||f.bind(e.scrollWrap,ha,e);y("initialZoomInEnd",function(){e.setContent(x[0],l-1);e.setContent(x[2],l+1);x[0].el.style.display=x[2].el.style.display="block";g.focus&&d.focus();f.bind(document,"keydown",e);w.transform&&f.bind(e.scrollWrap,"click",e);g.mouseUsed||f.bind(document,
"mousemove",yb);f.bind(window,"resize scroll",e);u("bindEvents")});e.setContent(x[1],l);e.updateCurrItem();u("afterInit");Ja||(Ga=setInterval(function(){Oa||Y||ga||t!==e.currItem.initialZoomLevel||e.updateSize()},1E3));f.addClass(d,"pswp--visible")}},close:function(){z&&(z=!1,Ua=!0,u("close"),f.unbind(window,"resize",e),f.unbind(window,"scroll",B.scroll),f.unbind(document,"keydown",e),f.unbind(document,"mousemove",yb),w.transform&&f.unbind(e.scrollWrap,"click",e),Y&&f.unbind(window,ba,e),u("unbindEvents"),
Yb(e.currItem,null,!0,e.destroy))},destroy:function(){u("destroy");xa&&clearTimeout(xa);d.setAttribute("aria-hidden","true");d.className=C;Ga&&clearInterval(Ga);f.unbind(e.scrollWrap,ha,e);f.unbind(window,"scroll",e);Bb();cb();Xa=null},panTo:function(a,b,c){c||(a>r.min.x?a=r.min.x:a<r.max.x&&(a=r.max.x),b>r.min.y?b=r.min.y:b<r.max.y&&(b=r.max.y));m.x=a;m.y=b;H()},handleEvent:function(a){a=a||window.event;if(B[a.type])B[a.type](a)},goTo:function(a){a=jb(a);var b=a-l;G=b;l=a;e.currItem=wa(l);F-=b;lb(L.x*
F);cb();N=!1;e.updateCurrItem()},next:function(){e.goTo(l+1)},prev:function(){e.goTo(l-1)},updateCurrZoomItem:function(a){a&&u("beforeChange",0);if(x[1].el.children.length){var b=x[1].el.children[0];ea=f.hasClass(b,"pswp__zoom-wrap")?b.style:null}else ea=null;r=e.currItem.bounds;R=t=e.currItem.initialZoomLevel;m.x=r.center.x;m.y=r.center.y;a&&u("afterChange")},invalidateCurrItems:function(){sa=!0;for(var a=0;3>a;a++)x[a].item&&(x[a].item.needsUpdate=!0)},updateCurrItem:function(a){if(0!==G){var b=
Math.abs(G);if(!(a&&2>b)){e.currItem=wa(l);La=!1;u("beforeChange",G);3<=b&&(E+=G+(0<G?-3:3),b=3);for(var c=0;c<b;c++)0<G?(a=x.shift(),x[2]=a,E++,Ma((E+2)*L.x,a.el.style),e.setContent(a,l-b+c+1+1)):(a=x.pop(),x.unshift(a),E--,Ma(E*L.x,a.el.style),e.setContent(a,l+b-c-1-1));ea&&1===Math.abs(G)&&(b=wa(Ha),b.initialZoomLevel!==t&&($a(b,q),ua(b),Ya(b)));G=0;e.updateCurrZoomItem();Ha=l;u("afterChange")}}},updateSize:function(a){if(!Ja&&g.modal){var b=f.getScrollY();ta!==b&&(d.style.top=b+"px",ta=b);if(!a&&
Va.x===window.innerWidth&&Va.y===window.innerHeight)return;Va.x=window.innerWidth;Va.y=window.innerHeight;d.style.height=Va.y+"px"}q.x=e.scrollWrap.clientWidth;q.y=e.scrollWrap.clientHeight;Xb();L.x=q.x+Math.round(q.x*g.spacing);L.y=q.y;lb(L.x*F);u("beforeResize");if(void 0!==E){for(var c,k=0;3>k;k++)a=x[k],Ma((k+E)*L.x,a.el.style),c=l+k-1,g.loop&&2<P()&&(c=jb(c)),(b=wa(c))&&(sa||b.needsUpdate||!b.bounds)?(e.cleanSlide(b),e.setContent(a,c),1===k&&(e.currItem=b,e.updateCurrZoomItem(!0)),b.needsUpdate=
!1):-1===a.index&&0<=c&&e.setContent(a,c),b&&b.container&&($a(b,q),ua(b),Ya(b));sa=!1}R=t=e.currItem.initialZoomLevel;if(r=e.currItem.bounds)m.x=r.center.x,m.y=r.center.y,H(!0);u("resize")},zoomTo:function(a,b,c,k,e){b&&(R=t,Za.x=Math.abs(b.x)-m.x,Za.y=Math.abs(b.y)-m.y,M(v,m));b=zb(a,!1);var d={};Wb("x",b,d,a);Wb("y",b,d,a);var n=t,g=m.x,h=m.y;Tb(d);b=function(b){1===b?(t=a,m.x=d.x,m.y=d.y):(t=(a-n)*b+n,m.x=(d.x-g)*b+g,m.y=(d.y-h)*b+h);e&&e(b);H(1===b)};c?db("customZoomTo",0,1,c,k||f.easing.sine.inOut,
b):b(1)}},Zb,mb,I={},Z={},J={},O={},Pa={},na=[],ya={},eb,za=[],Cb,Db,Eb,ab,fb,nb=0,gb=A(),Fb=0,Y,Gb,va,Na,ob,Aa,S,ga,$b,r,fa=A(),ea,N,Za=A(),Ba=A(),oa,Hb,pb,kb,qb,sc=function(a,b){return 25>Math.abs(a.x-b.x)&&25>Math.abs(a.y-b.y)},ac=function(a,b){Cb=Math.abs(a.x-b.x);Db=Math.abs(a.y-b.y);return Math.sqrt(Cb*Cb+Db*Db)},Bb=function(){ob&&(n(ob),ob=null)},bc=function(){if(Y&&(ob=Ka(bc),S)){var a=S.length;if(0!==a)if(M(I,S[0]),J.x=I.x-O.x,J.y=I.y-O.y,ga&&1<a){O.x=I.x;O.y=I.y;if(a=!J.x&&!J.y)a=S[1],a=
a.x===Z.x&&a.y===Z.y;if(!a){M(Z,S[1]);va||(va=!0,u("zoomGestureStarted"));a=ac(I,Z);a=1/$b*a*R;a>e.currItem.initialZoomLevel+e.currItem.initialZoomLevel/15&&(qb=!0);var b=1,c=Ub(),k=Vb();a<c?g.pinchToClose&&!qb&&R<=e.currItem.initialZoomLevel?(b=1-(c-a)/(c/1.2),da(b),u("onPinchClose",b),pb=!0):(b=(c-a)/c,1<b&&(b=1),a=c-c/3*b):a>k&&(b=(a-k)/(6*c),1<b&&(b=1),a=k+b*c);gb.x=.5*(I.x+Z.x);gb.y=.5*(I.y+Z.y);K.x+=gb.x-Ba.x;K.y+=gb.y-Ba.y;M(Ba,gb);m.x=wb("x",a);m.y=wb("y",a);Eb=a>t;t=a;H()}}else oa&&(Hb&&
(Hb=!1,10<=Math.abs(J.x)&&(J.x-=S[0].x-Pa.x),10<=Math.abs(J.y)&&(J.y-=S[0].y-Pa.y)),O.x=I.x,O.y=I.y,0!==J.x||0!==J.y)&&("v"===oa&&g.closeOnVerticalDrag&&"fit"===g.scaleMode&&t===e.currItem.initialZoomLevel?(K.y+=J.y,m.y+=J.y,a=cc(),ab=!0,u("onVerticalDrag",a),da(a),H()):(a=X(),b=I.x,c=I.y,50<a-mb&&(k=2<za.length?za.shift():{},k.x=b,k.y=c,za.push(k),mb=a),Na=!0,r=e.currItem.bounds,dc("x",J)||(dc("y",J),Tb(m),H())))}},ec=function(a,b){return!a||a.className&&-1<a.className.indexOf("pswp__scroll-wrap")?
!1:b(a)?a:ec(a.parentNode,b)},Ib={},fc=function(a,b){Ib.prevent=!ec(a.target,g.isClickableElement);u("preventDragEvent",a,b,Ib);return Ib.prevent},gc=function(a,b){b.x=a.pageX;b.y=a.pageY;b.id=a.identifier;return b},cc=function(){return 1-Math.abs((m.y-e.currItem.initialPosition.y)/(q.y/2))},hb={},tc={},pa=[],rb,Jb=function(a){for(;0<pa.length;)pa.pop();ca?(rb=0,na.forEach(function(a){0===rb?pa[0]=a:1===rb&&(pa[1]=a);rb++})):-1<a.type.indexOf("touch")?a.touches&&0<a.touches.length&&(pa[0]=gc(a.touches[0],
hb),1<a.touches.length&&(pa[1]=gc(a.touches[1],tc))):(hb.x=a.pageX,hb.y=a.pageY,hb.id="",pa[0]=hb);return pa},dc=function(a,b){var c,k=m[a]+b[a],d,n=0<b[a],f=fa.x+b.x,h=fa.x-ya.x,C,l;c=k>r.min[a]||k<r.max[a]?g.panEndFriction:1;k=m[a]+b[a]*c;if(g.allowPanToNext||t===e.currItem.initialZoomLevel)if(ea?"h"!==oa||"x"!==a||va||(n?(k>r.min[a]&&(c=g.panEndFriction,d=r.min[a]-v[a]),(0>=d||0>h)&&1<P()?(l=f,0>h&&f>ya.x&&(l=ya.x)):r.min.x!==r.max.x&&(C=k)):(k<r.max[a]&&(c=g.panEndFriction,d=v[a]-r.max[a]),(0>=
d||0<h)&&1<P()?(l=f,0<h&&f<ya.x&&(l=ya.x)):r.min.x!==r.max.x&&(C=k))):l=f,"x"===a)return void 0!==l&&(lb(l,!0),Aa=l===ya.x?!1:!0),r.min.x!==r.max.x&&(void 0!==C?m.x=C:Aa||(m.x+=b.x*c)),void 0!==l;N||Aa||t>e.currItem.fitRatio&&(m[a]+=b[a]*c)},uc=function(a){if(!("mousedown"===a.type&&0<a.button))if(Qa)a.preventDefault();else if(!fb||"mousedown"!==a.type){fc(a,!0)&&a.preventDefault();u("pointerDown");if(ca){var b=f.arraySearch(na,a.pointerId,"id");0>b&&(b=na.length);na[b]={x:a.pageX,y:a.pageY,id:a.pointerId}}a=
Jb(a);b=a.length;S=null;cb();Y&&1!==b||(Y=Hb=!0,f.bind(window,ba,e),Eb=qb=pb=ab=Aa=Na=Gb=va=!1,oa=null,u("firstTouchStart",a),M(v,m),K.x=K.y=0,M(O,a[0]),M(Pa,O),ya.x=L.x*F,za=[{x:O.x,y:O.y}],mb=Zb=X(),zb(t,!0),Bb(),bc());!ga&&1<b&&!N&&!Aa&&(R=t,va=!1,ga=Gb=!0,K.y=K.x=0,M(v,m),M(I,a[0]),M(Z,a[1]),Ba.x=.5*(I.x+Z.x),Ba.y=.5*(I.y+Z.y),Za.x=Math.abs(Ba.x)-m.x,Za.y=Math.abs(Ba.y)-m.y,$b=ac(I,Z))}},vc=function(a){a.preventDefault();if(ca){var b=f.arraySearch(na,a.pointerId,"id");-1<b&&(b=na[b],b.x=a.pageX,
b.y=a.pageY)}Y&&(a=Jb(a),oa||Na||ga?S=a:fa.x!==L.x*F?oa="h":(b=Math.abs(a[0].x-O.x)-Math.abs(a[0].y-O.y),10<=Math.abs(b)&&(oa=0<b?"h":"v",S=a)))},Ac=function(a){if(w.isOldAndroid){if(fb&&"mouseup"===a.type)return;-1<a.type.indexOf("touch")&&(clearTimeout(fb),fb=setTimeout(function(){fb=0},600))}u("pointerUp");fc(a,!1)&&a.preventDefault();var b;if(ca){var c=f.arraySearch(na,a.pointerId,"id");-1<c&&(b=na.splice(c,1)[0],navigator.pointerEnabled?b.type=a.pointerType||"mouse":(b.type={4:"mouse",2:"touch",
3:"pen"}[a.pointerType],b.type||(b.type=a.pointerType||"mouse")))}var k=Jb(a),c=k.length;"mouseup"===a.type&&(c=0);if(2===c)return S=null,!0;1===c&&M(Pa,k[0]);0!==c||oa||N||(b||("mouseup"===a.type?b={x:a.pageX,y:a.pageY,type:"mouse"}:a.changedTouches&&a.changedTouches[0]&&(b={x:a.changedTouches[0].pageX,y:a.changedTouches[0].pageY,type:"touch"})),u("touchRelease",a,b));a=-1;0===c&&(Y=!1,f.unbind(window,ba,e),Bb(),ga?a=0:-1!==Fb&&(a=X()-Fb));Fb=1===c?X():-1;a=-1!==a&&150>a?"zoom":"swipe";ga&&2>c&&
(ga=!1,1===c&&(a="zoomPointerUp"),u("zoomGestureEnded"));S=null;if(Na||va||N||ab)if(cb(),eb||(eb=wc()),eb.calculateSwipeSpeed("x"),ab)if(cc()<g.verticalDragRange)e.close();else{var d=m.y,n=kb;db("verticalDrag",0,1,300,f.easing.cubic.out,function(a){m.y=(e.currItem.initialPosition.y-d)*a+d;da((1-n)*a+n);H()});u("onVerticalDrag",1)}else{if((Aa||N)&&0===c){if(xc(a,eb))return;a="zoomPointerUp"}N||("swipe"!==a?yc():!Aa&&t>e.currItem.fitRatio&&zc(eb))}},wc=function(){var a,b,c={lastFlickOffset:{},lastFlickDist:{},
lastFlickSpeed:{},slowDownRatio:{},slowDownRatioReverse:{},speedDecelerationRatio:{},speedDecelerationRatioAbs:{},distanceOffset:{},backAnimDestination:{},backAnimStarted:{},calculateSwipeSpeed:function(k){1<za.length?(a=X()-mb+50,b=za[za.length-2][k]):(a=X()-Zb,b=Pa[k]);c.lastFlickOffset[k]=O[k]-b;c.lastFlickDist[k]=Math.abs(c.lastFlickOffset[k]);c.lastFlickSpeed[k]=20<c.lastFlickDist[k]?c.lastFlickOffset[k]/a:0;.1>Math.abs(c.lastFlickSpeed[k])&&(c.lastFlickSpeed[k]=0);c.slowDownRatio[k]=.95;c.slowDownRatioReverse[k]=
1-c.slowDownRatio[k];c.speedDecelerationRatio[k]=1},calculateOverBoundsAnimOffset:function(a,b){c.backAnimStarted[a]||(m[a]>r.min[a]?c.backAnimDestination[a]=r.min[a]:m[a]<r.max[a]&&(c.backAnimDestination[a]=r.max[a]),void 0!==c.backAnimDestination[a]&&(c.slowDownRatio[a]=.7,c.slowDownRatioReverse[a]=1-c.slowDownRatio[a],.05>c.speedDecelerationRatioAbs[a]&&(c.lastFlickSpeed[a]=0,c.backAnimStarted[a]=!0,db("bounceZoomPan"+a,m[a],c.backAnimDestination[a],b||300,f.easing.sine.out,function(b){m[a]=b;
H()}))))},calculateAnimOffset:function(a){c.backAnimStarted[a]||(c.speedDecelerationRatio[a]*=c.slowDownRatio[a]+c.slowDownRatioReverse[a]-c.slowDownRatioReverse[a]*c.timeDiff/10,c.speedDecelerationRatioAbs[a]=Math.abs(c.lastFlickSpeed[a]*c.speedDecelerationRatio[a]),c.distanceOffset[a]=c.lastFlickSpeed[a]*c.speedDecelerationRatio[a]*c.timeDiff,m[a]+=c.distanceOffset[a])},panAnimLoop:function(){Q.zoomPan&&(Q.zoomPan.raf=Ka(c.panAnimLoop),c.now=X(),c.timeDiff=c.now-c.lastNow,c.lastNow=c.now,c.calculateAnimOffset("x"),
c.calculateAnimOffset("y"),H(),c.calculateOverBoundsAnimOffset("x"),c.calculateOverBoundsAnimOffset("y"),.05>c.speedDecelerationRatioAbs.x&&.05>c.speedDecelerationRatioAbs.y&&(m.x=Math.round(m.x),m.y=Math.round(m.y),H(),bb("zoomPan")))}};return c},zc=function(a){a.calculateSwipeSpeed("y");r=e.currItem.bounds;a.backAnimDestination={};a.backAnimStarted={};if(.05>=Math.abs(a.lastFlickSpeed.x)&&.05>=Math.abs(a.lastFlickSpeed.y))return a.speedDecelerationRatioAbs.x=a.speedDecelerationRatioAbs.y=0,a.calculateOverBoundsAnimOffset("x"),
a.calculateOverBoundsAnimOffset("y"),!0;Ab("zoomPan");a.lastNow=X();a.panAnimLoop()},xc=function(a,b){var c;N||(nb=l);var d;if("swipe"===a){var n=O.x-Pa.x,h=10>b.lastFlickDist.x;30<n&&(h||20<b.lastFlickOffset.x)?d=-1:-30>n&&(h||-20>b.lastFlickOffset.x)&&(d=1)}var C;d&&(l+=d,0>l?(l=g.loop?P()-1:0,C=!0):l>=P()&&(l=g.loop?0:P()-1,C=!0),!C||g.loop)&&(G+=d,F-=d,c=!0);d=L.x*F;n=Math.abs(d-fa.x);c||d>fa.x===0<b.lastFlickSpeed.x?(n=0<Math.abs(b.lastFlickSpeed.x)?n/Math.abs(b.lastFlickSpeed.x):333,n=Math.min(n,
400),n=Math.max(n,250)):n=333;nb===l&&(c=!1);N=!0;u("mainScrollAnimStart");db("mainScroll",fa.x,d,n,f.easing.cubic.out,lb,function(){cb();N=!1;nb=-1;(c||nb!==l)&&e.updateCurrItem();u("mainScrollAnimComplete")});c&&e.updateCurrItem(!0);return c},yc=function(){var a=t,b=Ub(),c=Vb();t<b?a=b:t>c&&(a=c);var d,n=kb;if(pb&&!Eb&&!qb&&t<b)return e.close(),!0;pb&&(d=function(a){da((1-n)*a+n)});e.zoomTo(a,0,200,f.easing.cubic.out,d);return!0};Wa("Gestures",{publicMethods:{initGestures:function(){var a=function(a,
c,d,e,n){ja=a+c;ka=a+d;la=a+e;Ia=n?a+n:""};(ca=w.pointerEvent)&&w.touch&&(w.touch=!1);ca?navigator.pointerEnabled?a("pointer","down","move","up","cancel"):a("MSPointer","Down","Move","Up","Cancel"):w.touch?(a("touch","start","move","end","cancel"),V=!0):a("mouse","down","move","up");ba=ka+" "+la+" "+Ia;ha=ja;ca&&!V&&(V=1<navigator.maxTouchPoints||1<navigator.msMaxTouchPoints);e.likelyTouchDevice=V;B[ja]=uc;B[ka]=vc;B[la]=Ac;Ia&&(B[Ia]=B[la]);w.touch&&(ha+=" mousedown",ba+=" mousemove mouseup",B.mousedown=
B[ja],B.mousemove=B[ka],B.mouseup=B[la]);V||(g.allowPanToNext=!1)}}});var xa,Yb=function(a,b,c,k){xa&&clearTimeout(xa);Kb=Qa=!0;var n;a.initialLayout?(n=a.initialLayout,a.initialLayout=null):n=g.getThumbBoundsFn&&g.getThumbBoundsFn(l);var h=c?g.hideAnimationDuration:g.showAnimationDuration,C=function(){bb("initialZoom");c?(e.template.removeAttribute("style"),e.bg.removeAttribute("style")):(da(1),b&&(b.style.display="block"),f.addClass(d,"pswp--animated-in"),u("initialZoom"+(c?"OutEnd":"InEnd")));
k&&k();Qa=!1};h&&n&&void 0!==n.x?function(){var b=Ea,k=!e.currItem.src||e.currItem.loadError||g.showHideOpacity;a.miniImg&&(a.miniImg.style.webkitBackfaceVisibility="hidden");c||(t=n.w/a.w,m.x=n.x,m.y=n.y-Rb,e[k?"template":"bg"].style.opacity=.001,H());Ab("initialZoom");c&&!b&&f.removeClass(d,"pswp--animated-in");if(k)if(c)f[(b?"remove":"add")+"Class"](d,"pswp--animate_opacity");else setTimeout(function(){f.addClass(d,"pswp--animate_opacity")},30);xa=setTimeout(function(){u("initialZoom"+(c?"Out":
"In"));if(c){var e=n.w/a.w,g=m.x,l=m.y,q=t,p=kb,v=function(a){1===a?(t=e,m.x=n.x,m.y=n.y-ta):(t=(e-q)*a+q,m.x=(n.x-g)*a+g,m.y=(n.y-ta-l)*a+l);H();k?d.style.opacity=1-a:da(p-a*p)};b?db("initialZoom",0,1,h,f.easing.cubic.out,v,C):(v(1),xa=setTimeout(C,h+20))}else t=a.initialZoomLevel,M(m,a.initialPosition),H(),da(1),k?d.style.opacity=1:da(1),xa=setTimeout(C,h+20)},c?25:90)}():(u("initialZoom"+(c?"Out":"In")),t=a.initialZoomLevel,M(m,a.initialPosition),H(),d.style.opacity=c?0:1,da(1),h?setTimeout(function(){C()},
h):C())},Ra,Sa,Ta,Ca=[],Kb,Qa,Bc={index:0,errorMsg:'<div class="pswp__error-msg"><a href="%url%" target="_blank">The image</a> could not be loaded.</div>',forceProgressiveLoading:!1,preload:[1,1],getNumItemsFn:function(){return Ra.length}},wa,P,hc=function(){return{center:{x:0,y:0},max:{x:0,y:0},min:{x:0,y:0}}},$a=function(a,b,c){if(a.src&&!a.loadError){var d=!c;d&&(a.vGap||(a.vGap={top:0,bottom:0}),u("parseVerticalMargin",a));Sa=b.x;Ta=b.y-a.vGap.top-a.vGap.bottom;if(d){b=Sa/a.w;var e=Ta/a.h;a.fitRatio=
b<e?b:e;b=g.scaleMode;"orig"===b?c=1:"fit"===b&&(c=a.fitRatio);1<c&&(c=1);a.initialZoomLevel=c;a.bounds||(a.bounds=hc())}if(c){b=a.w*c;var e=a.h*c,n=a.bounds;n.center.x=Math.round((Sa-b)/2);n.center.y=Math.round((Ta-e)/2)+a.vGap.top;n.max.x=b>Sa?Math.round(Sa-b):n.center.x;n.max.y=e>Ta?Math.round(Ta-e)+a.vGap.top:n.center.y;n.min.x=b>Sa?0:n.center.x;n.min.y=e>Ta?a.vGap.top:n.center.y;d&&c===a.initialZoomLevel&&(a.initialPosition=a.bounds.center);return a.bounds}}else return a.w=a.h=0,a.initialZoomLevel=
a.fitRatio=1,a.bounds=hc(),a.initialPosition=a.bounds.center,a.bounds},sb=function(a,b,c,d,e,n){!b.loadError&&d&&(b.imageAppended=!0,ua(b,d),c.appendChild(d),n&&setTimeout(function(){b&&b.loaded&&b.placeholder&&(b.placeholder.style.display="none",b.placeholder=null)},500))},ic=function(a){a.loading=!0;a.loaded=!1;var b=a.img=f.createEl("pswp__img","img"),c=function(){a.loading=!1;a.loaded=!0;a.loadComplete?a.loadComplete(a):a.img=null;b=b.onload=b.onerror=null};b.onload=c;b.onerror=function(){a.loadError=
!0;c()};b.src=a.src;return b},jc=function(a,b){if(a.src&&a.loadError&&a.container)return b&&(a.container.innerHTML=""),a.container.innerHTML=g.errorMsg.replace("%url%",a.src),!0},ua=function(a,b,c){if(a.src){b||(b=a.container.lastChild);var d=c?a.w:Math.round(a.w*a.fitRatio);c=c?a.h:Math.round(a.h*a.fitRatio);a.placeholder&&!a.loaded&&(a.placeholder.style.width=d+"px",a.placeholder.style.height=c+"px");b.style.width=d+"px";b.style.height=c+"px"}},kc=function(){if(Ca.length){for(var a,b=0;b<Ca.length;b++)a=
Ca[b],a.holder.index===a.index&&sb(a.index,a.item,a.baseDiv,a.img,!1,a.clearPlaceholder);Ca=[]}};Wa("Controller",{publicMethods:{lazyLoadItem:function(a){a=jb(a);var b=wa(a);b&&(!b.loaded&&!b.loading||sa)&&(u("gettingData",a,b),b.src&&ic(b))},initController:function(){f.extend(g,Bc,!0);e.items=Ra=p;wa=e.getItemAt;P=g.getNumItemsFn;3>P()&&(g.loop=!1);y("beforeChange",function(a){var b=g.preload;a=null===a?!0:0<=a;var c=Math.min(b[0],P()),b=Math.min(b[1],P()),d;for(d=1;d<=(a?b:c);d++)e.lazyLoadItem(l+
d);for(d=1;d<=(a?c:b);d++)e.lazyLoadItem(l-d)});y("initialLayout",function(){e.currItem.initialLayout=g.getThumbBoundsFn&&g.getThumbBoundsFn(l)});y("mainScrollAnimComplete",kc);y("initialZoomInEnd",kc);y("destroy",function(){for(var a,b=0;b<Ra.length;b++)a=Ra[b],a.container&&(a.container=null),a.placeholder&&(a.placeholder=null),a.img&&(a.img=null),a.preloader&&(a.preloader=null),a.loadError&&(a.loaded=a.loadError=!1);Ca=null})},getItemAt:function(a){return 0<=a?void 0!==Ra[a]?Ra[a]:!1:!1},allowProgressiveImg:function(){return g.forceProgressiveLoading||
!V||g.mouseUsed||1200<screen.width},setContent:function(a,b){g.loop&&(b=jb(b));var c=e.getItemAt(a.index);c&&(c.container=null);var c=e.getItemAt(b),d;if(c){u("gettingData",b,c);a.index=b;a.item=c;var n=c.container=f.createEl("pswp__zoom-wrap");!c.src&&c.html&&(c.html.tagName?n.appendChild(c.html):n.innerHTML=c.html);jc(c);$a(c,q);if(!c.src||c.loadError||c.loaded)c.src&&!c.loadError&&(d=f.createEl("pswp__img","img"),d.style.opacity=1,d.src=c.src,ua(c,d),sb(b,c,n,d,!0));else{c.loadComplete=function(c){if(z){if(a&&
a.index===b){if(jc(c,!0)){c.loadComplete=c.img=null;$a(c,q);Ya(c);a.index===l&&e.updateCurrZoomItem();return}c.imageAppended?!Qa&&c.placeholder&&(c.placeholder.style.display="none",c.placeholder=null):w.transform&&(N||Qa)?Ca.push({item:c,baseDiv:n,img:c.img,index:b,holder:a,clearPlaceholder:!0}):sb(b,c,n,c.img,N||Qa,!0)}c.loadComplete=null;c.img=null;u("imageLoadComplete",b,c)}};if(f.features.transform){var h;h="pswp__img pswp__img--placeholder"+(c.msrc?"":" pswp__img--placeholder--blank");h=f.createEl(h,
c.msrc?"img":"");c.msrc&&(h.src=c.msrc);ua(c,h);n.appendChild(h);c.placeholder=h}c.loading||ic(c);e.allowProgressiveImg()&&(!Kb&&w.transform?Ca.push({item:c,baseDiv:n,img:c.img,index:b,holder:a}):sb(b,c,n,c.img,!0,!0))}Kb||b!==l?Ya(c):(ea=n.style,Yb(c,d||c.img));a.el.innerHTML="";a.el.appendChild(n)}else a.el.innerHTML=""},cleanSlide:function(a){a.img&&(a.img.onload=a.img.onerror=null);a.loaded=a.loading=a.img=a.imageAppended=!1}}});var qa,Lb={},Mb=function(a,b,c){var d=document.createEvent("CustomEvent");
d.initCustomEvent("pswpTap",!0,!0,{origEvent:a,target:a.target,releasePoint:b,pointerType:c||"touch"});a.target.dispatchEvent(d)};Wa("Tap",{publicMethods:{initTap:function(){y("firstTouchStart",e.onTapStart);y("touchRelease",e.onTapRelease);y("destroy",function(){Lb={};qa=null})},onTapStart:function(a){1<a.length&&(clearTimeout(qa),qa=null)},onTapRelease:function(a,b){if(b&&!Na&&!Gb&&!Oa){if(qa&&(clearTimeout(qa),qa=null,sc(b,Lb))){u("doubleTap",b);return}"mouse"===b.type?Mb(a,b,"mouse"):"BUTTON"===
a.target.tagName.toUpperCase()||f.hasClass(a.target,"pswp__single-tap")?Mb(a,b):(M(Lb,b),qa=setTimeout(function(){Mb(a,b);qa=null},300))}}}});var T;Wa("DesktopZoom",{publicMethods:{initDesktopZoom:function(){vb||(V?y("mouseUsed",function(){e.setupDesktopZoom()}):e.setupDesktopZoom(!0))},setupDesktopZoom:function(a){T={};y("bindEvents",function(){f.bind(d,"wheel mousewheel DOMMouseScroll",e.handleMouseWheel)});y("unbindEvents",function(){T&&f.unbind(d,"wheel mousewheel DOMMouseScroll",e.handleMouseWheel)});
e.mouseZoomedIn=!1;var b,c=function(){e.mouseZoomedIn&&(f.removeClass(d,"pswp--zoomed-in"),e.mouseZoomedIn=!1);1>t?f.addClass(d,"pswp--zoom-allowed"):f.removeClass(d,"pswp--zoom-allowed");n()},n=function(){b&&(f.removeClass(d,"pswp--dragging"),b=!1)};y("resize",c);y("afterChange",c);y("pointerDown",function(){e.mouseZoomedIn&&(b=!0,f.addClass(d,"pswp--dragging"))});y("pointerUp",n);a||c()},handleMouseWheel:function(a){if(t<=e.currItem.fitRatio)return g.modal&&(!g.closeOnScroll||Oa||Y?a.preventDefault():
U&&2<Math.abs(a.deltaY)&&(Ea=!0,e.close())),!0;a.stopPropagation();T.x=0;if("deltaX"in a)1===a.deltaMode?(T.x=18*a.deltaX,T.y=18*a.deltaY):(T.x=a.deltaX,T.y=a.deltaY);else if("wheelDelta"in a)a.wheelDeltaX&&(T.x=-.16*a.wheelDeltaX),T.y=a.wheelDeltaY?-.16*a.wheelDeltaY:-.16*a.wheelDelta;else if("detail"in a)T.y=a.detail;else return;zb(t,!0);var b=m.x-T.x,c=m.y-T.y;(g.modal||b<=r.min.x&&b>=r.max.x&&c<=r.min.y&&c>=r.max.y)&&a.preventDefault();e.panTo(b,c)},toggleDesktopZoom:function(a){a=a||{x:q.x/2+
ia.x,y:q.y/2+ia.y};var b=g.getDoubleTapZoom(!0,e.currItem),c=t===b;e.mouseZoomedIn=!c;e.zoomTo(c?e.currItem.initialZoomLevel:b,a,333);f[(c?"remove":"add")+"Class"](d,"pswp--zoomed-in")}}});var Cc={history:!0,galleryUID:1},ib,lc,Da,tb,Nb,mc,ub,Ob,Pb,aa,nc=function(){var a="",b;b=aa.hash.substring(1);var c={};b=b.replace("%5B","[");b=b.replace("%5D","]");b=b.replace(/([^|])(poster=|videoplayer)/mg,"$1|$2");b=b.match(/^!([\w\-[\]]+?\/(?:(\d+)(?=\/))?(https?:\/\/[^&]*)?([A-Z]{2}\/[_\w]*)?)/im);null!==
b?(a=b[1],a=a.substring(a.indexOf("/")+1,a.length),/^([A-Z]{2}\/[_\w]*)$/im.test(a)&&(a=a.replace("/","-")),jQuery.each(p,function(b,d){if("undefined"!==typeof d.contentID&&d.contentID=="jig-contentID-"+a||d.src==a)return c.pid=b,!1}),c.pid=parseInt(c.pid,10)):c.pid=0;return c},Qb=function(){Da&&clearTimeout(Da);if(Oa||Y)Da=setTimeout(Qb,500);else{tb?clearTimeout(lc):tb=!0;var a="!"+g.galleryUID+"/";if("undefined"!==typeof p[l].contentID){var b=/(?:jig-contentID)-(\w{2})-([^\s]*)/im.exec(p[l].contentID);
null!==b&&(a+=b[1]+"/"+b[2])}else a+=p[l].src;ub?(a=aa.href.split("#")[0]+"#"+a,aa.replace(a)):(-1===aa.hash.indexOf(a)&&(Pb=!0),aa.hash=a);ub=!0;lc=setTimeout(function(){tb=!1},60)}};Wa("History",{publicMethods:{initHistory:function(){f.extend(g,Cc,!0);if(g.history){aa=window.location;ub=Ob=Pb=!1;y("afterChange",e.updateURL);y("unbindEvents",function(){f.unbind(window,"hashchange",e.onHashChange)});var a=function(){mc=!0;Ob||(Pb?history.back():"pushState"in history?history.pushState("",document.title,
aa.pathname+aa.search):aa.hash="");ib&&clearTimeout(ib);Da&&clearTimeout(Da)};y("unbindEvents",function(){Ea&&a()});y("destroy",function(){mc||a()});y("firstUpdate",function(){l=nc().pid});setTimeout(function(){z&&f.bind(window,"hashchange",e.onHashChange)},40)}},onHashChange:function(){""===aa.hash.substring(1)?(Ob=!0,e.close()):tb||(Nb=!0,e.goTo(nc().pid),Nb=!1)},updateURL:function(){ib&&clearTimeout(ib);Da&&clearTimeout(Da);Nb||(ub?ib=setTimeout(Qb,800):Qb())}}});f.extend(e,rc)}});
(function(d,h){"function"===typeof define&&define.amd?define(h):"object"===typeof exports?module.exports=h():d.PhotoSwipeUI_Default=h()})(this,function(){return function(d,h){var p=this,ra=!1,f=!0,e,g,A,z,Ua,Ea,l,D=!0,E,K,v,m,ba,ha,B,q,t={barsSize:{top:44,bottom:"auto"},closeElClasses:["item","caption","zoom-wrap","ui","top-bar"],timeToIdle:4E3,timeToIdleOutside:1E3,loadingIndicatorDelay:1E3,addCaptionHTMLFn:function(d,e){if(!d.title)return e.children[0].innerHTML="",!1;e.children[0].innerHTML=d.title;
return!0},closeEl:!0,captionEl:!0,fullscreenEl:!0,zoomEl:!0,shareEl:!0,counterEl:!0,arrowEl:!0,preloaderEl:!0,tapToClose:!1,tapToToggleControls:!0,clickToCloseNonZoomable:!0,shareButtons:[{id:"facebook",label:"Share on Facebook",url:"https://www.facebook.com/sharer/sharer.php?u={{url}}"},{id:"twitter",label:"Tweet",url:"https://twitter.com/intent/tweet?text={{text}}&url={{url}}"},{id:"pinterest",label:"Pin it",url:"http://www.pinterest.com/pin/create/button/?url={{url}}&media={{image_url}}&description={{text}}"},
{id:"download",label:"Download image",url:"{{raw_image_url}}",download:!0}],getImageURLForShare:function(){return d.currItem.src||""},getPageURLForShare:function(){return window.location.href},getTextForShare:function(){return d.currItem.title||""},indexIndicatorSep:" / "},R,Fa=function(d){if(R)return!0;d=d||window.event;q.timeToIdle&&q.mouseUsed&&!K&&ka();for(var e,f=(d.target||d.srcElement).className,g,l=0;l<ma.length;l++)e=ma[l],e.onTap&&-1<f.indexOf("pswp__"+e.name)&&(e.onTap(),g=!0);g&&(d.stopPropagation&&
d.stopPropagation(),R=!0,setTimeout(function(){R=!1},h.features.isOldAndroid?600:30))},W=function(d,e,f){h[(f?"add":"remove")+"Class"](d,"pswp__"+e)},Ga=function(){var d=1===q.getNumItemsFn();d!==B&&(W(g,"ui--one-slide",d),B=d)},sa=function(){W(l,"share-modal--hidden",D)},F=function(){(D=!D)?(h.removeClass(l,"pswp__share-modal--fade-in"),setTimeout(function(){D&&sa()},300)):(sa(),setTimeout(function(){D||h.addClass(l,"pswp__share-modal--fade-in")},30));D||L();return!1},ia=function(e){e=e||window.event;
var f=e.target||e.srcElement;d.shout("shareLinkClick",e,f);if(!f.href)return!1;if(f.hasAttribute("download"))return!0;window.open(f.href,"pswp_share","scrollbars=yes,resizable=yes,toolbar=no,location=yes,width=550,height=420,top=100,left="+(window.screen?Math.round(screen.width/2-275):100));D||F();return!1},L=function(){var e="",f=d.options.shareButtons,h,g,m;if(location.hash){g=decodeURI(document.location.href);var q=g.split("#!");g=q[0]+"#!"+q[1]}else g=location.href;if("undefined"!==typeof d.options.socialButtons){var p=
d.options.socialButtons,f=[],p=p.toLowerCase(),p=p.split(""),q=jQuery.inArray("f",p),v=jQuery.inArray("t",p),z=jQuery.inArray("p",p),p=jQuery.inArray("g",p);~q&&(f[q]=d.options.shareButtons[0]);~v&&(f[v]=d.options.shareButtons[1]);~z&&(f[z]=d.options.shareButtons[2]);~p&&(f[p]=d.options.shareButtons[3]);"undefined"!==typeof d.options.shareButtons[4]&&f.push(d.options.shareButtons[4])}jQuery.each(f,function(f,l){"undefined"!==typeof l&&(m=(d.currItem.title||"")+(d.currItem.description?(d.currItem.title?
" ":"")+d.currItem.description:"")||document.title,h=l.url.replace("{{url}}",encodeURIComponent(g)).replace("{{facebook_url}}",encodeURIComponent(g.replace("#!",(-1===g.indexOf("?")?"?":"&")+"_escaped_fragment_="))).replace("{{image_url}}",encodeURIComponent(d.currItem.src||"")).replace("{{raw_image_url}}",d.currItem.src||"").replace("{{title}}",encodeURIComponent(d.currItem.title||document.title)).replace("{{description}}",encodeURIComponent(jQuery("<p>"+m.replace(/<a(?:.+?)href=['"](.+?)['"](?:.+?>)(.+?)(?:<\/a>)/mg,
"$2: $1")+"</p>").text())),e+='<a href="'+h+'" target="_blank" class="pswp__share--'+l.id+'"'+(l.download?"download":"")+">"+l.label+"</a>")});l.children[0].innerHTML=e;l.children[0].onclick=ia},x=function(d){for(var e=0;e<q.closeElClasses.length;e++)if(h.hasClass(d,"pswp__"+q.closeElClasses[e]))return!0},Ha,G,ja=0,ka=function(){clearTimeout(G);ja=0;K&&p.setIdle(!1)},la=function(d){d=d?d:window.event;d=d.relatedTarget||d.toElement;d&&"HTML"!==d.nodeName||(clearTimeout(G),G=setTimeout(function(){p.setIdle(!0)},
q.timeToIdleOutside))},Ia=function(){q.preloaderEl&&(U(!0),v("beforeChange",function(){clearTimeout(ha);ha=setTimeout(function(){d.currItem&&d.currItem.loading?(!d.allowProgressiveImg()||d.currItem.img&&!d.currItem.img.naturalWidth)&&U(!1):U(!0)},q.loadingIndicatorDelay)}),v("imageLoadComplete",function(e,f){d.currItem===f&&U(!0)}))},U=function(d){ba!==d&&(W(m,"preloader--active",!d),ba=d)},ca=function(e){var f=e.vGap;if(!d.likelyTouchDevice||q.mouseUsed||1200<screen.width){var l=q.barsSize;q.captionEl&&
"auto"===l.bottom?(z||(z=h.createEl("pswp__caption pswp__caption--fake"),z.appendChild(h.createEl("pswp__caption__center")),g.insertBefore(z,A),h.addClass(g,"pswp__ui--fit")),q.addCaptionHTMLFn(e,z,!0)?f.bottom=parseInt(z.clientHeight,10)||44:f.bottom=l.top):f.bottom="auto"===l.bottom?0:l.bottom;f.top=l.top}else f.top=f.bottom=0},Ja=function(){q.timeToIdle&&v("mouseUsed",function(){h.bind(document,"mousemove",ka);h.bind(document,"mouseout",la);Ha=setInterval(function(){ja++;2===ja&&p.setIdle(!0)},
q.timeToIdle/2)})},V=function(){v("onVerticalDrag",function(d){f&&.95>d?p.hideControls():!f&&.95<=d&&p.showControls()});var d;v("onPinchClose",function(e){f&&.9>e?(p.hideControls(),d=!0):d&&!f&&.9<e&&p.showControls()});v("zoomGestureEnded",function(){d=!1})},ma=[{name:"caption",option:"captionEl",onInit:function(d){A=d}},{name:"share-modal",option:"shareEl",onInit:function(d){l=d},onTap:function(){F()}},{name:"button--share",option:"shareEl",onInit:function(d){Ea=d},onTap:function(){F()}},{name:"button--zoom",
option:"zoomEl",onTap:d.toggleDesktopZoom},{name:"counter",option:"counterEl",onInit:function(d){Ua=d}},{name:"button--close",option:"closeEl",onTap:d.close},{name:"button--arrow--left",option:"arrowEl",onTap:d.prev},{name:"button--arrow--right",option:"arrowEl",onTap:d.next},{name:"button--fs",option:"fullscreenEl",onTap:function(){e.isFullscreen()?e.exit():e.enter()}},{name:"preloader",option:"preloaderEl",onInit:function(d){m=d}}],Ka=function(){var d,e,f,l=function(g){if(g)for(var l=g.length,m=
0;m<l;m++){d=g[m];e=d.className;for(var p=0;p<ma.length;p++)if(f=ma[p],-1<e.indexOf("pswp__"+f.name))if(q[f.option]){if(h.removeClass(d,"pswp__element--disabled"),f.onInit)f.onInit(d)}else h.addClass(d,"pswp__element--disabled")}};l(g.children);var m=h.getChildByClass(g,"pswp__top-bar");m&&l(m.children)};p.init=function(){h.extend(d.options,t,!0);q=d.options;g=h.getChildByClass(d.scrollWrap,"pswp__ui");v=d.listen;V();v("beforeChange",p.update);v("doubleTap",function(e){var f=d.currItem.initialZoomLevel;
d.getZoomLevel()!==f?d.zoomTo(f,e,333):d.zoomTo(q.getDoubleTapZoom(!1,d.currItem),e,333)});v("preventDragEvent",function(d,e,f){(e=d.target||d.srcElement)&&e.className&&-1<d.type.indexOf("mouse")&&(0<e.className.indexOf("__caption")||/(SMALL|STRONG|EM)/i.test(e.tagName))&&(f.prevent=!1)});v("bindEvents",function(){h.bind(g,"pswpTap click",Fa);h.bind(d.scrollWrap,"pswpTap",p.onGlobalTap);d.likelyTouchDevice||h.bind(d.scrollWrap,"mouseover",p.onMouseOver)});v("unbindEvents",function(){D||F();Ha&&clearInterval(Ha);
h.unbind(document,"mouseout",la);h.unbind(document,"mousemove",ka);h.unbind(g,"pswpTap click",Fa);h.unbind(d.scrollWrap,"pswpTap",p.onGlobalTap);h.unbind(d.scrollWrap,"mouseover",p.onMouseOver);e&&(h.unbind(document,e.eventK,p.updateFullscreen),e.isFullscreen()&&(q.hideAnimationDuration=0,e.exit()),e=null)});v("destroy",function(){q.captionEl&&(z&&g.removeChild(z),h.removeClass(A,"pswp__caption--empty"));l&&(l.children[0].onclick=null);h.removeClass(g,"pswp__ui--over-close");h.addClass(g,"pswp__ui--hidden");
p.setIdle(!1)});q.showAnimationDuration||h.removeClass(g,"pswp__ui--hidden");v("initialZoomIn",function(){q.showAnimationDuration&&h.removeClass(g,"pswp__ui--hidden")});v("initialZoomOut",function(){h.addClass(g,"pswp__ui--hidden")});v("parseVerticalMargin",ca);Ka();q.shareEl&&Ea&&l&&(D=!0);Ga();Ja();q.fullscreenEl&&(e||(e=p.getFullscreenAPI()),e?(h.bind(document,e.eventK,p.updateFullscreen),p.updateFullscreen(),h.addClass(d.template,"pswp--supports-fs")):h.removeClass(d.template,"pswp--supports-fs"));
Ia()};p.setIdle=function(d){K=d;W(g,"ui--idle",d)};p.update=function(){f&&d.currItem?(p.updateIndexIndicator(),q.captionEl&&(q.addCaptionHTMLFn(d.currItem,A),W(A,"caption--empty",!d.currItem.title)),ra=!0):ra=!1;D||F();Ga()};p.updateFullscreen=function(f){f&&setTimeout(function(){d.setScrollOffset(0,h.getScrollY())},50);h[(e.isFullscreen()?"add":"remove")+"Class"](d.template,"pswp--fs")};p.updateIndexIndicator=function(){q.counterEl&&(Ua.innerHTML=d.getCurrentIndex()+1+q.indexIndicatorSep+q.getNumItemsFn())};
p.onGlobalTap=function(e){e=e||window.event;var g=e.target||e.srcElement;R||(e.detail&&"mouse"===e.detail.pointerType?x(g)?d.close():h.hasClass(g,"pswp__img")&&(1===d.getZoomLevel()&&d.getZoomLevel()<=d.currItem.fitRatio?q.clickToCloseNonZoomable&&d.close():d.toggleDesktopZoom(e.detail.releasePoint)):(q.tapToToggleControls&&(f?p.hideControls():p.showControls()),q.tapToClose&&(h.hasClass(g,"pswp__img")||x(g))&&d.close()))};p.onMouseOver=function(d){d=d||window.event;W(g,"ui--over-close",x(d.target||
d.srcElement))};p.hideControls=function(){h.addClass(g,"pswp__ui--hidden");f=!1};p.showControls=function(){f=!0;ra||p.update();h.removeClass(g,"pswp__ui--hidden")};p.supportsFullscreen=function(){var d=document;return!!(d.exitFullscreen||d.mozCancelFullScreen||d.webkitExitFullscreen||d.msExitFullscreen)};p.getFullscreenAPI=function(){var e=document.documentElement,f;e.requestFullscreen?f={enterK:"requestFullscreen",exitK:"exitFullscreen",elementK:"fullscreenElement",eventK:"fullscreenchange"}:e.mozRequestFullScreen?
f={enterK:"mozRequestFullScreen",exitK:"mozCancelFullScreen",elementK:"mozFullScreenElement",eventK:"mozfullscreenchange"}:e.webkitRequestFullscreen?f={enterK:"webkitRequestFullscreen",exitK:"webkitExitFullscreen",elementK:"webkitFullscreenElement",eventK:"webkitfullscreenchange"}:e.msRequestFullscreen&&(f={enterK:"msRequestFullscreen",exitK:"msExitFullscreen",elementK:"msFullscreenElement",eventK:"MSFullscreenChange"});f&&(f.enter=function(){E=q.closeOnScroll;q.closeOnScroll=!1;if("webkitRequestFullscreen"===
this.enterK)d.template[this.enterK](Element.ALLOW_KEYBOARD_INPUT);else return d.template[this.enterK]()},f.exit=function(){q.closeOnScroll=E;return document[this.exitK]()},f.isFullscreen=function(){return document[this.elementK]});return f}}});
(function(d){d.fn.JIGphotoSwipe=function(h){var p=this,ra=d(p[0]).closest(".justified-image-grid"),f=d.extend(!0,{},h),e=function(e){var f=[];p.filter('[rel="'+e+'"]').each(function(e){e=d(this);var g=e.find("img"),h=e.find("img").attr("alt"),p=e.attr("title"),z=e.attr("data-wh").split("x"),v="jig-overflow"==e.parent().attr("class")?e.closest(".jig-imageContainer").attr("class"):e.attr("class"),v=/(?:jig-contentID)-(\w{2})-([^\s]*)/im.exec(v),g={src:e.attr("href"),w:parseInt(z[0],10),h:parseInt(z[1],
10),msrc:g.attr("src")};null!=v&&(g.contentID=v[0]);h&&(g.title=h);p&&(g.description=p);g.el=e[0];f.push(g)});return f},g=function(e){e.preventDefault();var f=d(e.target).closest(".jig-imageContainer").attr("class"),f=/(?:jig-contentID)-(\w{2})-([^\s]*)/im.exec(f),g=d(e.target).closest("a.jig-link");e=g.attr("rel");f=null!=f?f[0]:g.attr("href");A(f,e);return!1},A=function(g,p,A){var l=e(p),D,E=!1;if(0==l.length)return!1;d.each(l,function(d,e){if("undefined"!==typeof e.contentID&&e.contentID==g||e.src==
g)return h.index=d,!1});h.galleryUID=p;h.getThumbBoundsFn=function(e){if("jig-overflow"==d(l[e].el).parent().attr("class")){var f=l[e].el.getElementsByTagName("img")[0];e=d(window).scrollTop();f=f.getBoundingClientRect();return{x:f.left,y:f.top+e,w:f.width}}return{x:d(window).width()/2,y:d(window).height()/2+d(window).scrollTop(),w:0}};h.addCaptionHTMLFn=function(d,e){var f=[];"undefined"!==typeof d.title&&f.push(d.title);"undefined"!==typeof d.description&&f.push("<small>"+d.description+"</small>");
if(0==f.length)return e.children[0].innerText="",!1;e.children[0].innerHTML=f.join("<br/>");return!0};h.shareButtons=[{id:"facebook",label:"Share on Facebook",url:"https://www.facebook.com/sharer/sharer.php?u={{facebook_url}}"},{id:"twitter",label:"Tweet",url:"https://twitter.com/intent/tweet?text={{title}}&url={{url}}"},{id:"pinterest",label:"Pin it",url:"http://www.pinterest.com/pin/create/button/?url={{url}}&media={{image_url}}&description={{description}}"},{id:"googleplus",label:"Share on Google+",
url:"https://plus.google.com/share?url={{url}}"}];"undefined"!==typeof h.allowDownload&&!0===h.allowDownload&&h.shareButtons.push({id:"download",label:"Download image",url:"{{raw_image_url}}",download:!0});if(A){if(h.showAnimationDuration=0,"undefined"==typeof f.closeOnScroll||1==f.closeOnScroll)h.closeOnScroll=!1,D=!0}else h.showAnimationDuration="undefined"==typeof f.showAnimationDuration?333:f.showAnimationDuration;p=d(l[h.index].el);"jig-overflow"==p.parent().attr("class")&&"0px"!==p.find("img").css("margin-left")&&
(E=!0);E||"undefined"!==typeof h.aspectRatioMismatch&&!0===h.aspectRatioMismatch?(h.showHideOpacity=!0,h.mainClass="hidePsPlaceholder"):(h.showHideOpacity="undefined"==typeof f.showHideOpacity?!1:f.showHideOpacity,h.mainClass="undefined"==typeof f.mainClass?"":f.mainClass);d(".pswp").removeAttr("style");d.fn.JIGphotoSwipe.gallery=new PhotoSwipe(d(".pswp")[0],PhotoSwipeUI_Default,l,h);d.fn.JIGphotoSwipe.gallery.init();1==D&&setTimeout(function(){d.fn.JIGphotoSwipe.gallery.options.closeOnScroll=!0},
2E3)};(function(){if(0===d(".pswp").length){var e="undefined"!==typeof h.captionAlign?" pswp__ca_"+h.captionAlign:" pswp__ca_center";d("body").append('<div class="pswp" tabindex="-1" role="dialog" aria-hidden="true"><div class="pswp__bg"></div><div class="pswp__scroll-wrap"><div class="pswp__container"><div class="pswp__item"></div><div class="pswp__item"></div><div class="pswp__item"></div></div><div class="pswp__ui pswp__ui--hidden'+e+'"><div class="pswp__top-bar"><div class="pswp__counter"></div><span class="pswp__button pswp__button--close" title="Close (Esc)"></span><span class="pswp__button pswp__button--share" title="Share"></span><span class="pswp__button pswp__button--fs" title="Toggle fullscreen"></span><span class="pswp__button pswp__button--zoom" title="Zoom in/out"></span><div class="pswp__preloader"><div class="pswp__preloader__icn"><div class="pswp__preloader__cut"><div class="pswp__preloader__donut"></div></div></div></div></div><div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap"><div class="pswp__share-tooltip"></div></div><span class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)"></span><span class="pswp__button pswp__button--arrow--right" title="Next (arrow right)"></span><div class="pswp__caption"><div class="pswp__caption__center"></div></div></div></div></div>')}ra.off("click.photoswipe").on("click.photoswipe",
"a.jig-link",g);var f="",p,e=location.hash,e=e.replace("%5B","["),e=e.replace("%5D","]"),e=e.replace(/([^|])(poster=|videoplayer)/mg,"$1|$2");p=e.match(/^#!([\w\-[\]]+?\/(?:(\d+)(?=\/))?(https?:\/\/[^&]*)?([A-Z]{2}\/[_\w]*)?)/im);null!==p&&(f=p[1],f=f.substring(f.indexOf("/")+1,f.length),/^([A-Z]{2}\/[_\w]*)$/im.test(f)&&(f=f.replace("/","-")));f="jig-contentID-"+f;(e=e.substring(2,e.indexOf("/")))&&f&&A(f,e,!0)})()}})(jQuery);